name: build-latex build and publish

on:
    push:
        branches: [ main ]
    
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Build & push build-latex image
            uses: mr-smithers-excellent/docker-build-push@v6
            with:
              image: blackapple113/build-latex
              tags: v2, latest
              registry: docker.io
              dockerfile: build-latex/Dockerfile
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}